services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springboot

    ports:
      - 3307:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - app-net


  # API Spring Boot
  api:
    image: leos51/api:latest
    container_name: spring-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/springboot
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8081:9090"
    networks:
      - app-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/persons" ]
      interval: 30s
      timeout: 10s
      retries: 3

  # Application Web
  web:
    image: leos51/webdemo:latest
    container_name: webdemo-app
    depends_on:
      api:
        condition: service_healthy
    environment:
      API_URL: http://api:9090
    ports:
      - "8080:8080"
    networks:
      - app-net


volumes:
  mysql-data:
networks:
  app-net:
    driver: bridge