spring.application.name=webDemo

# port du serveur web
server.port=9001

# niveau de level logging
logging.level.root=error

#niveau de level pour le package
logging.level.training.afpa.cda24060=INFO
# niveau de logging por les requetes HTTP

logging.level.org.springframework.client.RestTemplate=DEBUG
# niveau de logging pour TOMCAT
logging.level.org.springframework.boot.web.embedded.tomcat=INFO

training.afpa.cda24060.webdemo.apiURL=${API_URL:http://localhost:9090}


# affichage d'une page d'erreurs
spring.web.error.include-exception=true
spring.web.error.include-stacktrace=always